    THIS LINE SHOULD EXIST

    THIS LINE SHOULD EXIST

THIS LINE SHOULD EXIST

    THIS LINE SHOULD EXIST

    THIS LINE SHOULD EXIST

#if OTHER_SHIT
    THIS LINE SHOULD EXIST
#elif ENABLED_DIRECTIVE
    THIS LINE SHOULD EXIST
#elif MORE_SHIT
    THIS LINE SHOULD EXIST
#else
    THIS LINE SHOULD EXIST
#endif

#if (OTHER_SHIT)
    THIS LINE SHOULD EXIST
#elif (ENABLED_DIRECTIVE)
    THIS LINE SHOULD EXIST
#elif (MORE_SHIT)
    THIS LINE SHOULD EXIST
#else
    THIS LINE SHOULD EXIST
#endif

#if OTHER_SHIT
    THIS LINE SHOULD EXIST
#elif MORE_SHIT
    THIS LINE SHOULD EXIST
#elif ENABLED_DIRECTIVE
    THIS LINE SHOULD EXIST
#else
    THIS LINE SHOULD EXIST
#endif

#if (OTHER_SHIT)
    THIS LINE SHOULD EXIST
#elif (MORE_SHIT)
    THIS LINE SHOULD EXIST
#elif (ENABLED_DIRECTIVE)
    THIS LINE SHOULD EXIST
#else
    THIS LINE SHOULD EXIST
#endif

    THIS LINE SHOULD EXIST

    THIS LINE SHOULD EXIST
