    THIS LINE SHOULD EXIST
    THIS LINE SHOULD EXIST
    THIS LINE SHOULD EXIST
    THIS LINE SHOULD EXIST
#if OTHER_SHIT
    THIS LINE SHOULD NOT EXIST
#elif ENABLED_DIRECTIVE
    THIS LINE SHOULD EXIST
#elif MORE_SHIT
    THIS LINE SHOULD NOT EXIST
#else
#endif

#if (OTHER_SHIT)
    THIS LINE SHOULD NOT EXIST
#elif (ENABLED_DIRECTIVE)
    THIS LINE SHOULD EXIST
#elif (MORE_SHIT)
    THIS LINE SHOULD NOT EXIST
#else
#endif

#if OTHER_SHIT
    THIS LINE SHOULD NOT EXIST
#elif MORE_SHIT
    THIS LINE SHOULD NOT EXIST
#elif ENABLED_DIRECTIVE
    THIS LINE SHOULD EXIST
#else
#endif

#if (OTHER_SHIT)
    THIS LINE SHOULD NOT EXIST
#elif (MORE_SHIT)
    THIS LINE SHOULD NOT EXIST
#elif (ENABLED_DIRECTIVE)
    THIS LINE SHOULD EXIST
#else
#endif

    THIS LINE SHOULD EXIST
    THIS LINE SHOULD EXIST
